# Tipos de dato

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])
arr.dtype

dtype('int64')

Podemos observar que numpy detecta los tipos de dato en automatico. Pero tambien podemos modificarlo:

In [3]:
arr = np.array([1,2,3,4], dtype="float64")
arr.dtype

dtype('float64')

In [4]:
arr

array([1., 2., 3., 4.])

In [7]:
original = np.array([0, 1,2,3,4])
original

array([0, 1, 2, 3, 4])

In [8]:
floatValues = original.astype(np.float64)
floatValues

array([0., 1., 2., 3., 4.])

In [9]:
booleans = original.astype(np.bool_)
booleans

array([False,  True,  True,  True,  True])

In [11]:
text = original.astype(np.string_)
text

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S21')

In [12]:
integers = text.astype(np.int8)
integers

array([0, 1, 2, 3, 4], dtype=int8)

Claramente los valores tienen que estar en un formato correcto para poder transformarse

In [13]:
test = np.array(["Hola", "2", "3"])
test.astype(np.int8)

ValueError: invalid literal for int() with base 10: 'Hola'