# Dimensiones

Existen diferentes tipos de dimensiones y cada una de ellas tiene nombres.

* Dimension 0 = Scalar (Un unico valor)
* Dimension 1 = Vector
* Dimension 2 = Matriz
* Dimendion 3 = ?
* Dimension N = Tensor

4D suele usarse para manipulacion de imagenes

In [1]:
import numpy as np

In [3]:
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

In [5]:
vector = np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

In [7]:
matriz = np.array([[1,2,3], [1,2,3]])
print(matriz)
matriz.ndim

[[1 2 3]
 [1 2 3]]


2

In [8]:
tensor = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])
print(tensor)
tensor.ndim

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


3

## Agregar o eliminar dimensiones

In [9]:
vector = np.array([1,2,3], ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [11]:
expand = np.expand_dims(np.array([1,2,3]), axis=0)
print(expand)
expand.ndim

[[1 2 3]]


2

In [12]:
expand2 = np.expand_dims(np.array([1,2,3]), axis=1)
print(expand2)
expand2.ndim

[[1]
 [2]
 [3]]


2

Reducir dimensiones

In [13]:
print(vector, vector.ndim)
vector_2 = np.squeeze(vector)
print(vector_2, vector_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1
