# Crear arrays con NumPy

In [1]:
import numpy as np

In [3]:
# Start, End not inclusive, Step
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [8]:
np.zeros(3)

np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [9]:
np.ones(3)

np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.linspace(0, 10, 100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [12]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
# Valores de 0 a 1
np.random.rand()
np.random.rand(4)
np.random.rand(4, 4)

array([[0.21590721, 0.91869091, 0.85788044, 0.80273166],
       [0.85963479, 0.89038367, 0.34557077, 0.82691962],
       [0.9172194 , 0.35931016, 0.35646145, 0.77064865],
       [0.7146588 , 0.47401713, 0.43125153, 0.30979357]])

In [20]:
# Obtener un valor aleatorio entre un rango
np.random.randint(1, 15)

8

In [21]:
np.random.randint(1, 100, [3, 3])

array([[47,  7, 25],
       [29, 77, 27],
       [95, 74, 44]])