In [2]:
import numpy as np

In [3]:
arr = np.random.randint(1, 10, (3, 2))

In [4]:
arr.shape

(3, 2)

In [5]:
arr.reshape(1, 6)

array([[3, 6, 1, 2, 6, 6]])

In [6]:
arr

array([[3, 6],
       [1, 2],
       [6, 6]])

In [7]:
arr.reshape(2, 3)

array([[3, 6, 1],
       [2, 6, 6]])

In [8]:
np.reshape(arr, (1, 6))

array([[3, 6, 1, 2, 6, 6]])

In [9]:
arr

array([[3, 6],
       [1, 2],
       [6, 6]])

In [10]:
np.reshape(arr, (2, 3), "C")

array([[3, 6, 1],
       [2, 6, 6]])

In [11]:
np.reshape(arr, (2, 3), "F")

# 1 4 
# 2 5
# 3 6

# 1 3 5 
# 2 4 6

array([[3, 6, 2],
       [1, 6, 6]])

In [12]:
np.reshape(arr, (2, 3), "A")

array([[3, 6, 1],
       [2, 6, 6]])

Tener en cuenta que la dimension tiene que ser similar, es decir, multiplos correctos del valor.

V = N * M