In [1]:
import numpy as np

In [3]:
arr = np.random.randint(1, 20, 10)

In [6]:
matriz = arr.reshape(2, 5)
matriz

array([[16, 17, 14, 15,  9],
       [16,  7, 11,  1,  1]])

In [7]:
arr.max()

17

In [8]:
arr.min()

1

In [10]:
# Envias axis 0 o 1, y te dice el max por columna o fila
matriz.max(1)

array([17, 16])

In [11]:
arr.argmax()

1

In [12]:
arr

array([16, 17, 14, 15,  9, 16,  7, 11,  1,  1])

In [15]:
matriz.argmax(0)

array([0, 0, 0, 0, 0])

Todo lo anterior tiene 'min'.

A los ejes puedes enviarlo o no.

In [17]:
arr

array([16, 17, 14, 15,  9, 16,  7, 11,  1,  1])

In [18]:
arr.ptp() # max - min

16

In [19]:
matriz.ptp(0)

array([ 0, 10,  3, 14,  8])

In [24]:
arr.sort()
arr

array([ 1,  1,  7,  9, 11, 14, 15, 16, 16, 17])

In [22]:
np.percentile(arr, 50) # La mediana en este caso. 0 a 100

12.5

In [25]:
np.median(arr)

12.5

In [26]:
np.median(matriz, 1)

array([ 7., 16.])

In [29]:
np.std(arr) ** 2

33.01000000000001

In [28]:
np.var(arr)

33.010000000000005

In [30]:
np.mean(arr)

10.7

In [32]:
a = np.array([[1,2], [3,4]])
b = np.array([5, 6])

In [33]:
np.concatenate((a, b), axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [34]:
a.ndim

2

In [35]:
b.ndim

1

In [36]:
b = np.expand_dims(b, axis=0)

In [37]:
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [38]:
np.concatenate((a, b), axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [40]:
b

array([[5, 6]])

In [41]:
b.T

array([[5],
       [6]])

In [39]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])